
# shintomap Example app 01
# - Most basic map with colored polygons based on a column in the data
# - Labels on hovering
# - Button on the map for a help popup

#- Load dependencies
library(shiny)
library(softui)
library(leaflet)

# loads this package
devtools::load_all()

# EHV geo (in git)
geo <- readRDS("geo_Eindhoven.rds")


#---- Shiny app -----
ui <- softui::simple_page(
  softui::box(title = "shintomap", icon = bsicon("geo-alt-fill"), width = 6,

              shintoMapUI("map", height = 800),
              radioButtons("switch", "Gebieden", choices = c("Ja","Nee"), selected = "Ja"),

              verbatimTextOutput("txt_out")
              )
)

server <- function(input, output, session) {

  # To inspect what reactives are globally generated by leaflet
  output$txt_out <- renderPrint({
    reactiveValuesToList(input)
  })

  # Step 1: make a base map (not reactive, can be made outside the server module)
  # shintoBaseMap makes a leaflet() object with a few standard selected layers,
  # and sets the view (before adding data; this helps with the UX of the map,
  # otherwise we might see the whole earth briefly before data are actually loaded)
  my_base_map <- shintomap::shintoBaseMap(set_view = list(
    lng = 5.463155,
    lat = 51.4497,
    zoom = 12
  )) %>%
  addEasyButtonBar(   # Adds buttons on the map.
    shintomap::map_easy_button(session$ns("btn_help"),
                    icon_file = "question-circle-fill.svg",
                    label = "Click here for help")
  )

  observeEvent(input$btn_help, {
    showModal(
      softui::modal(
        title = "Help",
        tags$p("This is a shintomap!")
      )
    )
  })

  # Call the shintomap module
  callModule(shintomap::shintoMapModule, "map",
             base_map = my_base_map,
             border = reactive(geo$grens),  # optional but highly recommended for look and feel

             # label_function shows something on hovering.
             # Can be part of a layer or global for all layers, like this
             # label_function is always a function of data and ...
             label_function = reactive(function(data,...)data$bu_naam),

             # The layers object is a *list of reactives*.
             # In this example we have just one layer (so one reactive in the list)
             layers = list(

               # Layer: gebouwen
               reactive(

                 # In this example all inputs are static, but any of these
                 # could be reactives (input$somevalue, somechoice(), etc).),
                 # see other examples
                 list(
                   data = geo$buurten,
                   toggle = input$switch == "Ja",
                   group = "area_layer",
                   geom = "Polygons",
                   id_column = "bu_code",
                   color_column = "a_inw",

                   color_function = list(
                     palfunction = "shinto_auto_color",
                     palette_function = "parula",
                     reverse = TRUE,
                     opacity = 0.8
                   ),
                   legend = list(
                     toggle = TRUE,
                     title = "Aantal inwoners",
                     position = "bottomright",
                     opacity = 0.9
                   )

                 )

               )

             )
  )


}

shinyApp(ui, server)
